spring:
  # todo 配置自己的数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_database
    username: root
    password: 123456
  # todo 配置Redis
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      password: 123456
#      database: 1
# 配置运行端口
server:
  port: 8080

# 阿里云OSS配置
aliyun:
  # todo 记得修改成自己的阿里云配置
  access-key-id: your_access_key_id
  endpoint: "https://oss-cn-beijing.aliyuncs.com"
  secret-access-key: your_access_key_secret
  bucket-name: your_bucket_name

# mybatis配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: not_null
